// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: KafkaMessage.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace Proto.Models
{

    [global::ProtoBuf.ProtoContract()]
    public partial class KafkaMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public MessageType MsgType { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Source { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4)]
        public int RetryCount { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Payload { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue("")]
        public string DatetimeCreatedUtc { get; set; } = "";

        [global::ProtoBuf.ProtoContract()]
        public enum MessageType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"TEST")]
            Test = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"ERROR")]
            Error = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"EVENT")]
            Event = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"COMMAND")]
            Command = 3,
        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
